[programs.devnet]
myepicproject = "7kyoBhx9Ti77WJE7W1EN7hcsTgXNf2JC8GoEkLBWcugC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/lrazovic/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
